export const LOAD_CATS_SUCCESS = 'LOAD_CATS_SUCCESS';
export const LOAD_CATS_FAILURE = 'LOAD_CATS_FAILURE';
export const LOAD_HOBBIES_SUCCESS = 'LOAD_HOBBIES_SUCCESS';
export const LOAD_HOBBIES_FAILURE = 'LOAD_HOBBIES_FAILURE';
export const UPDATE_CAT_SUCCESS = 'UPDATE_CAT_SUCCESS';
export const UPDATE_CAT_FAILURE = 'UPDATE_CAT_FAILURE';